#!/bin/bash

#Clean
rm -f bin/*
rm -f lib/*
rm -f includes/*

#Initialize
mkdir bin 2> /dev/null
mkdir lib 2> /dev/null
mkdir includes 2> /dev/null

#log
make -C log
cp log/log.so lib/log.so
cp log/liblog.a lib/liblog.a
cp log/headers/log.hpp includes/log.hpp

#common
make -C common
cp common/common.so lib/common.so
cp common/ccommon.so lib/ccommon.so
cp common/libcommon.a lib/libcommon.a
cp common/libccommon.a lib/libccommon.a
cp common/headers/common.h includes/common.h
cp common/headers/common.hpp includes/common.hpp

#ml
make -C ml
cp ml/ml.so lib/ml.so
cp ml/libml.a lib/libml.a
cp ml/headers/ml.h includes/ml.h
cp ml/headers/ml.hpp includes/ml.hpp

#dtkmlc
make -C dtkmlc
cp dtkmlc/dtkmlc bin/dtkmlc

#project
make -C project
cp project/project bin/project

#test
./.scripts/test.sh